spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_prod
    username: sfg_prod_user
    # Prefer to use an Environment Variable for password or encryption in a production environment
    password: guru
    platform: mysql
  jpa:
    hibernate:
      # Prevent hibernate from making DDL changes - but validate will make it check the database schema
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    # Will ensure the SQL statements are NOT shown in the console
    show-sql: false